select * from Cursos--1v1 = 1 // 1v2 = 2
select * from Condiciones --Regular = 3

use Gestus
SET LANGUAGE 'Español'
--LEGAJO - NOM - APE - CURSO (2) -CONDI (3) - GRUPO - VISIBLE (0)

INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80409,'Aguado', 'Ana Carolina', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80692,'Aguero', 'Nemesis Ayelen', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78984,'Aldeco Molina', 'Juan Ignacio', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (81385,'Aliendro', 'Javier Ignacio', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (54362,'Altamirano', 'Ricardo Gaston', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (74804,'Antoniazzi', 'Cristian Gaston', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (70108,'Arce', 'Rocio Anahi', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (81319,'Aresqueta', 'Juan Esteban', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79794,'Atencio', 'Federico', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78275,'Balan', 'Camila Ariana', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79329,'Barcia', 'Luciana', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (77023,'Benitez', 'Alain Patric', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78941,'Bertossi', 'Agostina', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79437,'Burgoa Cortez', 'Nicole', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78383,'Bustos', 'Abril Rocio', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79947,'Cabrera Burgos', 'Daniel Ezequiel', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80212,'Cacciavillani', 'Filipo', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (54398,'Caceres', 'Nicolas Horacio', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80798,'Callejo', 'Lina Gisela', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (72940,'Camporeale', 'Nicolas Eric', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79193,'Castillo Miranda', 'Maria Paula', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (81049,'Castro', 'Daniela Veronica', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78650,'Catalano Tortelli', 'Camila', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79447,'Cavatorta', 'Blas', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78736,'Cavillon', 'Maria Azul', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79960,'Cazon Revollo', 'Facundo Miguel', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (51605,'Cortabarria', 'Joaquin Emiliano', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80986,'Coscolla', 'Maximiliano Luis', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79736,'Crespin', 'Pablo Agustin', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78347,'Cristin', 'Dana Martina', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78534,'Di Chiazza', 'Lisandro Agustin', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80301,'Di Terlizzi', 'Dana Guadalupe', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79927,'Dorvilus', 'Djems', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78414,'Ferrigno', 'Maria Nazarena', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (71092,'Figueroa', 'Nicolás Ezequiel', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (77686,'Franchi', 'Juan Gabriel', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (76238,'Garcia', 'Catalina', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (65002,'García', 'Lautaro Hernán', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (74217,'Garcia', 'Sebastian Eduardo', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80144,'Ghibaudo Lopez', 'Rosario Ayelen', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (69978,'Ghigo', 'Roxana del Valle', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (77793,'Israel', 'Kief Weler Stevensky', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79354,'Israel', 'Mudge Murdrelle', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (64624,'Katogui', 'Agustin', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (74820,'Laquiz Abraham', 'Amiel Ernesto', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (77376,'Leguiza', 'Florencia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (73197,'Leon Tolentino', 'Thalia Jhanet', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80192,'Lescano', 'Malena Stefanía', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (77735,'Madrid Zavaley', 'Macarena Daniela', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78570,'Maiz Ricaldez', 'Kevin Arnold', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (81388,'Mandolini', 'Enzo Guido', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (71906,'Marin Acosta', 'Francisco', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (81524,'Mayer', 'Alfredo Gustavo', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80335,'Mayon', 'Santiago Ignacio', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78861,'Medina Quinteros', 'Alexandra', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78526,'Michalik Malara', 'Sathya Cecilia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (75720,'Misericordia', 'Hector Leandro', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79168,'Montenegro', 'Mayra Cecilia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (75701,'Moran', 'Maria Belén', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (61776,'Moyano', 'Jessica Patricia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (70107,'Muñoz Rivadero', 'Maria De Los Angeles', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78916,'Navarro Alonso', 'Sofía', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79242,'Nuñez', 'Guadalupe Milagros', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (77591,'Nuñez', 'Hector Mateo', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80025,'Ochoa', 'Alejandro Nicolas', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79218,'Ortega', 'Cecilia Maria', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80142,'Ottosen', 'Fiona Lucia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78985,'Pacheco Luna', 'Maria Constanza', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80607,'Pedroso', 'Cecilia Florencia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78734,'Peralta', 'Tomas Daniel', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80318,'Peretti', 'Fabricio Alejandro', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (71241,'Perotti Bernardini', 'Robertino', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79888,'Pierre Louis', 'Virginia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78556,'Pistone', 'Ezequiel Ivan', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79422,'Pollastrinni', 'Enzo Maximiliano', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79454,'Prosdocimo', 'Celeste', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78529,'Pussetto', 'Victoria Isabel', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79279,'Rodriguez', 'Sofia Luciana', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78929,'Rojas Pervetic', 'Antonio Hector Domingo', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78392,'Ruiz', 'Candela Milagros', 2 , 3, null,'01/04/2018',0)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (73198,'Saavedra Villarreal', 'Mariel Daniela Victoria', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (71681,'Sanchez', 'Maira Lelis', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (76623,'Sarmiento', 'Romina Julia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80432,'Sireix', 'Rocio Camila', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (69137,'Suarez', 'Augusto Alejandro', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78477,'Tornato', 'Sofia Milagros', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80366,'Torres Reigosa', 'Alvaro', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (75474,'Torres', 'Sofía Helena', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79261,'Velazquez', 'Laura Natalia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (64187,'Vera Romero', 'Debora Cynthia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78445,'Vera', 'Camila Jenifer', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (59553,'Vilchez', 'Jeremias Adrian', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (80650,'Vincent', 'Clara Heliette', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (78396,'Viscarra Sanchez', 'Rocio Agostina', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79660,'Wismer', 'Kimberly Patricia', 2 , 3, null,'01/04/2018',1)
INSERT INTO Alumnos(legajo, apellido, nombre, id_curso, id_condicion , grupo , fecha_ingreso, visible) VALUES (79979,'Yapura', 'Alvaro Alexis', 2 , 3, null,'01/04/2018',1)
